<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;

    protected $fillable = ['body', 'completed'];

    protected $touches = ['project'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($task) {
            Activity::create([
               'project_id' => $task->project->id,
               'description' => 'created_task'
            ]);
        });

        static::updated(function($task) {
            if (! $task->completed) return;
            Activity::create([
                'project_id' => $task->project->id,
                'description' => 'completed_task'
            ]);
        });
    }


    public function project()
    {
        return $this->belongsTo(Projects::class, 'projects_id');
    }

    public function path()
    {
        return "/projects/{$this->project->id}/tasks/{$this->id}";
    }

}
